apiVersion: apps/v1
kind: Deployment
metadata:
  name: '${DEPLOYMENT_WEB@microservice-blog-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    app: '${DEPLOYMENT_WEB@microservice-blog-config}'
    moduleid: microservice-blog-web-service
    version: 1.70.0-account-page-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: '${DEPLOYMENT_WEB@microservice-blog-config}'
  template:
    metadata:
      labels:
        app: '${DEPLOYMENT_WEB@microservice-blog-config}'
    spec:
      containers:
        -
          name: app
          image: 'repoflow/microservice-blog-web-container:1.70.0-account-page-prod'
          env:
            -
              name: HOST
              value: '${HOST@microservice-config}'
            -
              name: BASE_ROUTE_APP
              value: '${BASE_ROUTE_APP@microservice-blog-config}'
            -
              name: INTERNAL_PORT_APP
              value: '${INTERNAL_PORT_APP@microservice-blog-config}'
            -
              name: EXTERNAL_URL_GRAPH
              value: '${EXTERNAL_URL_GRAPH@microservice-blog-config}'
            -
              name: EXTERNAL_URL_EVENTS
              value: '${EXTERNAL_URL_EVENTS@microservice-blog-config}'
            -
              name: INTERNAL_URL_GRAPH
              value: '${INTERNAL_URL_GRAPH@microservice-blog-config}'
            -
              name: INTERNAL_URL_EVENTS
              value: '${INTERNAL_URL_EVENTS@microservice-blog-config}'
          ports:
            -
              containerPort: '${INTERNAL_PORT_APP@microservice-blog-config}'
