apiVersion: v1
kind: Service
metadata:
  name: '${SERVICE_WEB@microservice-blog-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-blog-web-service
    version: 1.70.0-master
spec:
  type: NodePort
  selector:
    app: '${DEPLOYMENT_WEB@microservice-blog-config}'
  ports:
    -
      name: microservice-blog-web-port
      port: '${INTERNAL_PORT_APP@microservice-blog-config}'
